# Generated by Django 4.2.1 on 2023-06-04 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BVField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('home_country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentPortalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zip_code', models.CharField(editable=False, max_length=20)),
                ('street', models.CharField(editable=False, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('passport_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SocialSecurityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_start_date', models.DateField()),
                ('coverage_end_date', models.DateField()),
                ('certificate_number', models.CharField(max_length=255)),
                ('issuing_authority', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TravelDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TripDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubmitComplianceResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('compliance_request_id', models.CharField(max_length=255)),
                ('government_portal_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.governmentportaldata')),
            ],
        ),
        migrations.CreateModel(
            name='SubmitComplianceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_request_id', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('compliance_types', models.JSONField()),
                ('government_portal_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.governmentportaldata')),
            ],
        ),
        migrations.CreateModel(
            name='SSField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employer')),
                ('personal_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personalinformation')),
                ('social_security_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.socialsecurityinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employer')),
                ('personal_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personalinformation')),
                ('social_security_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.socialsecurityinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_request_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('host_country', models.CharField(max_length=255)),
                ('issue', models.CharField(max_length=255)),
                ('created_date', models.DateField()),
                ('last_updated', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PWNField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_purpose', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('visa_type', models.CharField(max_length=255)),
                ('previous_visits', models.BooleanField()),
                ('emergency_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.emergencycontact')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employer')),
                ('home_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pwn_fields_home', to='api.location')),
                ('host_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pwn_fields_host', to='api.location')),
                ('personal_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personalinformation')),
                ('travel_dates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.traveldate')),
            ],
        ),
        migrations.CreateModel(
            name='PWNData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_purpose', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('visa_type', models.CharField(max_length=255)),
                ('previous_visits', models.BooleanField()),
                ('emergency_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.emergencycontact')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employer')),
                ('home_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pwn_data_home', to='api.location')),
                ('host_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pwn_data_host', to='api.location')),
                ('personal_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personalinformation')),
                ('travel_dates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.traveldate')),
            ],
        ),
        migrations.CreateModel(
            name='InitiateComplianceResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('compliance_request_id', models.CharField(max_length=255)),
                ('compliance_types', models.JSONField()),
                ('next_step_api_endpoint', models.URLField()),
                ('next_step_http_method', models.CharField(max_length=255)),
                ('next_step_request_body', models.JSONField()),
                ('government_portal_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.governmentportaldata')),
            ],
        ),
        migrations.CreateModel(
            name='InitiateComplianceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(max_length=255)),
                ('compliance_types', models.CharField(choices=[('PWN', 'PWN'), ('SS', 'SS'), ('BV', 'BV')], max_length=255)),
                ('home_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiate_compliance_requests_home', to='api.location')),
                ('host_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiate_compliance_requests_host', to='api.location')),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.passport')),
                ('travel_dates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.traveldate')),
                ('trip_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tripdetails')),
            ],
        ),
        migrations.AddField(
            model_name='governmentportaldata',
            name='pwn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pwndata'),
        ),
        migrations.AddField(
            model_name='governmentportaldata',
            name='ss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ssdata'),
        ),
        migrations.CreateModel(
            name='FormFieldsComplianceResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('compliance_type', models.JSONField()),
                ('required_fields_bv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_fields_bv', to='api.bvfield')),
                ('required_fields_pwn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_fields_pwn', to='api.pwnfield')),
                ('required_fields_ss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_fields_ss', to='api.ssfield')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceRequestsResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('total_results', models.IntegerField()),
                ('page_size', models.IntegerField()),
                ('page_number', models.IntegerField()),
                ('requests', models.ManyToManyField(to='api.request')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceRequestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.request')),
            ],
        ),
        migrations.AddField(
            model_name='bvfield',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employer'),
        ),
        migrations.AddField(
            model_name='bvfield',
            name='personal_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personalinformation'),
        ),
        migrations.AddField(
            model_name='bvfield',
            name='social_security_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.socialsecurityinfo'),
        ),
    ]
